### ISSUE TITLE
Suggested enhancement: Have syntax highlighter recognize successorML-style '(*)' one-line/inline comments

### ISSUE THREAD

**Issue by m-bob** [valcioffi/vscode-standard-ml#2]
Thanks for this extension! It works well and I like and use it. But I'd like to suggest/request an enhancement to the existing syntax highlighting.

One-line (and inline) comments using (*) to designate a comment, such as

(*) run sml -Cparser.succ-ml=true

let val x = 1 and y = 2 in x + y end; (*) 2: val it = 3 : int

are a nice extension to SML, permitting better documentation.

Unfortunately, they're not compatible with the current syntax highlighter. (The highlighter looks for an ending '*)' which it doesn't find.)

May I request an enhancement to permit the use of this comment style? Perhaps also italicize comments :) ?

Thanks!

Murray

**Comment by valcioffi** [comment]
Hello m-bob, thanks for your feedback and your suggestions!

The [definition of Standard ML](https://smlfamily.github.io/sml97-defn.pdf) does not reference single-line comments. However, some implementations such as Successor ML have them.

Changing the default highlighting to detect single-line comments could cause confusion to users using those implementations that don't expect them. To solve this, it should be possible to add an option to enable their highlighting only if wanted.
I'll start working on that!

As for the italicized comments: thanks, that would be a nice detail.

**Comment by m-bob** [comment]
Hi Valentino!

I'm so grateful you're willing to do that! Thank you! I agree that having
the option to permit or not to permit is the right way to go.

FWIW, I asked the Perplexity AI if it could create a syntax highlighter for
SML that could accept (*) as a marker for single/in-line comments. I
haven't checked its answer, but it returned a lengthy response which looks
plausible.

This was my query:

"Can you write a syntax highlighter for VSCode for the language SML? I need
one that can recognize one-line/inline comments using (*) as the comment
marker? (Comments of this form are allowed in successorML.)"

I didn't ask Perplexity about italicizing comments. You probably don't need
or want Perplexity's "help," but if you think it might save you some time,
-- or if you're just curious -- I can send Perplexity's response to you --
or you could try the query (or one like it) yourself.

I've found that Perplexity (like OpenAI's ChatGPT) doesn't usually get
things correct right off the bat. But a dialog with it can work -- or one
can fix its response if you know the domain sufficiently.

Sorry for the long Perplexity digression. (I'm not affiliated with them in
any way.)

I'm just thrilled you like my suggestion!

Again, thank you!

Murray

**Comment by valcioffi** [comment]
The suggestions have been implemented in #3. Once `v1.0.1` is released (I still have to fix a comment-related bug I noticed while working on this) the changes will be live. You just have to enable the `SML.successorML` setting to use them.

**Comment by m-bob** [comment]
Thank you so much! I think single/in-line comments are really useful.

Again, thank you!

Murray
